module.exports = {
  apps: [
    {
      name: "parse-server",
      script: "server.js",
      exec_mode: "fork",
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 5000,
      watch: false,
      out_file: "logs/parse-server.out.log",
      error_file: "logs/parse-server.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      env_production: {
        NODE_ENV: process.env.NODE_ENV,
        NODE_PORT: process.env.NODE_PORT,
        PARSE_SERVER_DATABASE_URI: process.env.PARSE_SERVER_DATABASE_URI,
        PARSE_SERVER_URL: process.env.PARSE_SERVER_URL,
        PARSE_SERVER_APPLICATION_ID: process.env.PARSE_SERVER_APPLICATION_ID,
        PARSE_SERVER_MASTER_KEY: process.env.PARSE_SERVER_MASTER_KEY,
        PARSE_SERVER_CLIENT_KEY: process.env.PARSE_SERVER_CLIENT_KEY,
        PARSE_SERVER_JAVASCRIPT_KEY: process.env.PARSE_SERVER_JAVASCRIPT_KEY,
        PARSE_SERVER_FILE_KEY: process.env.PARSE_SERVER_FILE_KEY,
        PARSE_SERVER_APP_NAME: process.env.PARSE_SERVER_APP_NAME,
        PARSE_SERVER_USER: process.env.PARSE_SERVER_USER,
        PARSE_SERVER_PASSWORD: process.env.PARSE_SERVER_PASSWORD,
        PARSE_SERVER_CLOUD: process.env.PARSE_SERVER_CLOUD,
        CORS_WHITELIST: process.env.CORS_WHITELIST,
      },
    },
  ],
};
